baseurl: '/'
permalink: pretty
title: 'Strategic Defense Corporation'
tagline: 'The Best Defense is a Good Offense'
url: 'https://strategicdefense.co'
excerpt_separator: <!--more-->
#logo: "/images/logo/logo-color-nobg.png" - doent jive with seo-tag

logo:
  mobile: "/images/favicon-big.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "/images/logo/logo-color-nobg.png"
  desktop_height: "32px"
  desktop_width: "200px"


home:
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  posts:
    output: true
    permalink: /blog/:name

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
